[discord]
token = "xxxxxx-your-discord-bot-token"
message_style = "multiline" # options are: "multiline", "oneline", "text"

[messagestyles]
	[messagestyles.rich]
	chat_message_ready_room_color = [75, 78, 82]
	chat_message_marine_color = [50, 127, 180]
	chat_message_alien_color = [246, 92, 0]
	chat_message_spectator_color = [211, 215, 207]
	player_join_color = [67, 181, 129]
	player_leave_color = [237, 72, 102]
	status_color = [250, 166, 26]

	[messagestyles.text]
	chat_message_format = "%s __[%t]__ **%p**: %m" # %p - player, %m - message, %t - teamspecific prefix, %s - serverspecific prefix
	chat_message_ready_room_prefix = "RR"
	chat_message_marine_prefix = "M"
	chat_message_alien_prefix = "A"
	chat_message_spectator_prefix = "S"
	player_join_format = "%s %p joined %m"
	player_leave_format = "%s %p left %m"

[httpserver]
address = ":8080"

[steam]
web_api_key = "xxxxxx-your-steam-web-api-key" # leave empty to deactivate steam avatars

[servers]
    [servers.example1]
    channelID = "1645231543324534623"
    statusChannelID = ""
    admins = ["Brute#9034", "Wooza#2865", "Las#0029", "125786284395462656"]
    keyword_notifications = [ ["@admin" "@op"], ["My Admin Role", "Brute#9034", "125786284395462656"], ]
    muted = ["Sandyclawz#1347"]
    server_chat_message_prefix = ""
    server_status_message_prefix = "<:apheriox:298852163759898624> "
    server_icon_url = "https://cdn.discordapp.com/icons/164863821276512267/9a7f55887cb50e053e1b7b14b86af199.png" # leave empty for guild icon

    [servers.example2]
    channelID = "1645231543324534624"
